## This file is part of Rabbit Hole.

##     Rabbit Hole is free software: you can redistribute it and/or modify
##     it under the terms of the GNU General Public License as published by
##     the Free Software Foundation, either version 3 of the License, or
##     (at your option) any later version.

##     Rabbit Hole is distributed in the hope that it will be useful,
##     but WITHOUT ANY WARRANTY; without even the implied warranty of
##     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##     GNU General Public License for more details.

##     You should have received a copy of the GNU General Public License
##     along with Rabbit Hole.  If not, see <http://www.gnu.org/licenses/>.
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sat Mar 17 19:53:29 2012

import wx
from os import listdir
from ObjectListView import ObjectListView,ColumnDefn
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class PrefDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PrefDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.prefNotebook = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.prefNotebook, -1)
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Default Plugin:")
        self.DefaultPlugin = wx.ComboBox(self.notebook_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Request timeout:")
        self.Timeout = wx.SpinCtrl(self.notebook_1_pane_1, -1, "", min=0, max=100)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Pages:")
        self.Pages = wx.SpinCtrl(self.notebook_1_pane_1, -1, "", min=0, max=100)
        self.notebook_1_pane_2 = wx.Panel(self.prefNotebook, -1)
        self.ListEnabled = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.SUNKEN_BORDER)
        self.ListDisabled = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.SUNKEN_BORDER)
        self.button_3 = wx.Button(self.notebook_1_pane_2, -1, "Switch")
        self.prefNotebook_pane_3 = wx.Panel(self.prefNotebook, -1)
        self.label_5 = wx.StaticText(self.prefNotebook_pane_3, -1, "Host:")
        self.TransmHost = wx.TextCtrl(self.prefNotebook_pane_3, -1, "")
        self.label_5_copy = wx.StaticText(self.prefNotebook_pane_3, -1, "Port:")
        self.TransmPort = wx.TextCtrl(self.prefNotebook_pane_3, -1, "")
        self.label_5_copy_copy = wx.StaticText(self.prefNotebook_pane_3, -1, "Username:")
        self.TransmUser = wx.TextCtrl(self.prefNotebook_pane_3, -1, "")
        self.label_5_copy_copy_1 = wx.StaticText(self.prefNotebook_pane_3, -1, "Password:")
        self.TransmPass = wx.TextCtrl(self.prefNotebook_pane_3, -1, "")
        self.Button_Apply = wx.Button(self, -1, "Apply")
        self.Button_Cancel = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.ButtonSwitch, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.ButtonApply, self.Button_Apply)
        self.Bind(wx.EVT_BUTTON, self.ButtonCancel, self.Button_Cancel)
        # end wxGlade
        
        self.config = self.Parent.ReadConfig()
        self.plugins = listdir('plugins')
        for i in range(len(self.plugins)):
            self.plugins[i] = self.plugins[i].replace('.json','')
        self.DefaultPlugin.SetItems(self.plugins)
        self.DefaultPlugin.SetSelection(self.plugins.index(self.config['default']))
        self.Pages.SetValue(self.config['pages'])
        self.Timeout.SetValue((self.config['timeout']))
        if self.config.has_key('transmission'):
            self.TransmPass.SetValue(self.config['transmission']['pass'])
            self.TransmUser.SetValue(self.config['transmission']['user'])
            self.TransmHost.SetValue(self.config['transmission']['host'])
            self.TransmPort.SetValue(self.config['transmission']['port'])
        #set lists
        self.indexE = 0
        self.indexD = 0
        self.ListDisabled.InsertColumn(0,"Disabled Plugins",width=200)
        self.ListEnabled.InsertColumn(0,"Enabled Plugins",width=200)
        
        for i in self.plugins:
            if i in self.config['DisabledPlugins']:
                self.ListDisabled.InsertStringItem(self.indexD,i)
                self.indexD+=1
            else:
                self.ListEnabled.InsertStringItem(self.indexE,i)
                self.indexE+=1
                
        
    def __set_properties(self):
        # begin wxGlade: PrefDialog.__set_properties
        self.SetTitle("Rabbit Hole - Preferences")
        self.ListEnabled.SetMinSize((200, 150))
        self.ListDisabled.SetMinSize((200, 150))
        self.TransmHost.SetMinSize((200, 24))
        self.TransmPort.SetMinSize((200, 24))
        self.TransmUser.SetMinSize((200, 24))
        self.TransmPass.SetMinSize((200, 24))
        # end wxGlade
        self.Button_Apply.SetDefault()

    def __do_layout(self):
        # begin wxGlade: PrefDialog.__do_layout
        grid_sizer_4 = wx.FlexGridSizer(4, 3, 10, 0)
        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_6 = wx.FlexGridSizer(6, 4, 10, 0)
        grid_sizer_8 = wx.FlexGridSizer(3, 1, 10, 5)
        grid_sizer_9 = wx.FlexGridSizer(1, 2, 23, 5)
        grid_sizer_5 = wx.FlexGridSizer(5, 4, 5, 5)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.DefaultPlugin, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.Timeout, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.Pages, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_5)
        grid_sizer_9.Add(self.ListEnabled, 1, wx.EXPAND, 0)
        grid_sizer_9.Add(self.ListDisabled, 1, wx.EXPAND, 0)
        grid_sizer_9.AddGrowableRow(0)
        grid_sizer_9.AddGrowableCol(0)
        grid_sizer_9.AddGrowableCol(1)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_8.Add(self.button_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_8.Add((10, 10), 0, 0, 0)
        self.notebook_1_pane_2.SetSizer(grid_sizer_8)
        grid_sizer_8.AddGrowableRow(0)
        grid_sizer_8.AddGrowableCol(0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add(self.TransmHost, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_5_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add(self.TransmPort, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_5_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add(self.TransmUser, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_5_copy_copy_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add(self.TransmPass, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        self.prefNotebook_pane_3.SetSizer(grid_sizer_6)
        self.prefNotebook.AddPage(self.notebook_1_pane_1, "General")
        self.prefNotebook.AddPage(self.notebook_1_pane_2, "Super Search")
        self.prefNotebook.AddPage(self.prefNotebook_pane_3, "Transmission")
        grid_sizer_4.Add(self.prefNotebook, 1, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.Button_Apply, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_7.Add(self.Button_Cancel, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(grid_sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        self.SetSizer(grid_sizer_4)
        grid_sizer_4.Fit(self)
        grid_sizer_4.AddGrowableRow(1)
        grid_sizer_4.AddGrowableCol(1)
        self.Layout()
        # end wxGlade

    def ButtonSwitch(self, event): # wxGlade: PrefDialog.<event_handler>
        selectedDisabled = self.ListDisabled.GetFirstSelected()
        selectedEnabled = self.ListEnabled.GetFirstSelected()
        if selectedEnabled >=0:
            self.ListEnabled.GetItemText(selectedEnabled)
            self.ListDisabled.InsertStringItem(self.indexD,str(self.ListEnabled.GetItemText(selectedEnabled)))
            self.ListEnabled.DeleteItem(selectedEnabled)
            self.indexD+=1
            self.indexE-=1
        if selectedDisabled>=0:
            self.ListDisabled.GetItemText(selectedDisabled)
            self.ListEnabled.InsertStringItem(self.indexD,str(self.ListDisabled.GetItemText(selectedDisabled)))
            self.ListDisabled.DeleteItem(selectedDisabled)
            self.indexE+=1
            self.indexD-=1            
        
    def ButtonApply(self, event): # wxGlade: PrefDialog.<event_handler>
        disabledPlugins = []
        for i in range(self.ListDisabled.GetItemCount()):
            disabledPlugins.append(self.ListDisabled.GetItemText(i))
        self.config['DisabledPlugins'] = disabledPlugins
        self.config['default'] = self.DefaultPlugin.GetValue()
        self.config['timeout'] = self.Timeout.GetValue()
        self.config['pages'] = self.Pages.GetValue()
        self.config['transmission'] = {}
        self.config['transmission']['pass'] = self.TransmPass.GetValue()
        self.config['transmission']['user'] = self.TransmUser.GetValue()
        self.config['transmission']['host'] = self.TransmHost.GetValue()
        self.config['transmission']['port'] = self.TransmPort.GetValue()
        self.Parent.WriteConfig(self.config)
        self.Parent.tc = None
        self.EndModal(wx.ID_OK)

    def ButtonCancel(self, event): # wxGlade: PrefDialog.<event_handler>
        self.EndModal(wx.ID_CANCEL)

# end of class PrefDialog


