## This file is part of Rabbit Hole.

##     Rabbit Hole is free software: you can redistribute it and/or modify
##     it under the terms of the GNU General Public License as published by
##     the Free Software Foundation, either version 3 of the License, or
##     (at your option) any later version.

##     Rabbit Hole is distributed in the hope that it will be useful,
##     but WITHOUT ANY WARRANTY; without even the implied warranty of
##     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##     GNU General Public License for more details.

##     You should have received a copy of the GNU General Public License
##     along with Rabbit Hole.  If not, see <http://www.gnu.org/licenses/>.
#!/usr/bin/env python
#
# -*- coding: US-ASCII -*-
#
# generated by wxGlade 9756a246126b on Sun Jul 15 18:32:39 2012
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainFrame import MainFrame

if __name__ == "__main__":
    RabbitHole = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MainFrame(None, wx.ID_ANY, "")
    RabbitHole.SetTopWindow(frame_3)
    frame_3.Show()
    RabbitHole.MainLoop()
