## This file is part of Rabbit Hole.

##     Rabbit Hole is free software: you can redistribute it and/or modify
##     it under the terms of the GNU General Public License as published by
##     the Free Software Foundation, either version 3 of the License, or
##     (at your option) any later version.

##     Rabbit Hole is distributed in the hope that it will be useful,
##     but WITHOUT ANY WARRANTY; without even the implied warranty of
##     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##     GNU General Public License for more details.

##     You should have received a copy of the GNU General Public License
##     along with Rabbit Hole.  If not, see <http://www.gnu.org/licenses/>.
# -*- coding: us-ascii -*-
# generated by wxGlade 300a4438fc64 on Wed Mar 14 10:28:15 2012

import wx
from ObjectListView import ObjectListView, ColumnDefn
from utils import *
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class SearchPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SearchPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.torrList = ObjectListView(self, -1, style=wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
                #Prepare columns
        self.torrList.SetColumns([
            ColumnDefn("Category","left",120,"category"),
            ColumnDefn("Name","left",500,"name"),
            ColumnDefn("Size","left",90,"size",stringConverter=formatSize),
            ColumnDefn("Seeders","left",60,"seeders",stringConverter="%d"),
            ColumnDefn("Leechers","left",60,"leechers",stringConverter="%d")])
        self.torrList.SetEmptyListMsg("")

    def __set_properties(self):
        # begin wxGlade: SearchPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SearchPanel.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.torrList, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        # end wxGlade

# end of class SearchPanel
